# Zaparoo Frontend
# Copyright (c) 2026 Wizzo Pty Ltd and the Zaparoo Project contributors.
# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      tokio:
        patterns: ["tokio*"]
      tracing:
        patterns: ["tracing*"]
      cxx-qt:
        patterns: ["cxx*"]
      serde:
        patterns: ["serde*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
