# Zaparoo Frontend
# Copyright (c) 2026 Wizzo Pty Ltd and the Zaparoo Project contributors.
# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

[toolchain]
channel    = "1.90.0"
components = ["rustfmt", "clippy"]
targets    = ["armv7-unknown-linux-gnueabihf"]
profile    = "minimal"
